{{- if .Values.global.vpaEnabled }}
apiVersion: "autoscaling.k8s.io/v1beta2"
kind: VerticalPodAutoscaler
metadata:
  name: node-local-dns
  namespace: {{ .Release.Namespace }}
  annotations:
      resources.gardener.cloud/mode: Ignore
{{- end }}
